# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc.ui'
#
# Created: Wed Feb  9 23:58:20 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 617)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.select_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_lineEdit.sizePolicy().hasHeightForWidth())
        self.select_lineEdit.setSizePolicy(sizePolicy)
        self.select_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.select_lineEdit.setObjectName(_fromUtf8("select_lineEdit"))
        self.horizontalLayout_8.addWidget(self.select_lineEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.select_pushButton = QtGui.QPushButton(self.centralwidget)
        self.select_pushButton.setObjectName(_fromUtf8("select_pushButton"))
        self.horizontalLayout_5.addWidget(self.select_pushButton)
        self.refresh_pushButton = QtGui.QPushButton(self.centralwidget)
        self.refresh_pushButton.setObjectName(_fromUtf8("refresh_pushButton"))
        self.horizontalLayout_5.addWidget(self.refresh_pushButton)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.opt_recursive = QtGui.QCheckBox(self.centralwidget)
        self.opt_recursive.setObjectName(_fromUtf8("opt_recursive"))
        self.verticalLayout_2.addWidget(self.opt_recursive)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.opt_size = QtGui.QSpinBox(self.centralwidget)
        self.opt_size.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.opt_size.setMaximum(500)
        self.opt_size.setObjectName(_fromUtf8("opt_size"))
        self.horizontalLayout_6.addWidget(self.opt_size)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.treeView = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_9.addWidget(self.treeView)
        self.status = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status.setFont(font)
        self.status.setText(_fromUtf8(""))
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName(_fromUtf8("status"))
        self.verticalLayout_9.addWidget(self.status)
        spacerItem = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.output_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.output_lineEdit.setObjectName(_fromUtf8("output_lineEdit"))
        self.horizontalLayout_11.addWidget(self.output_lineEdit)
        self.output_pushButton = QtGui.QPushButton(self.centralwidget)
        self.output_pushButton.setObjectName(_fromUtf8("output_pushButton"))
        self.horizontalLayout_11.addWidget(self.output_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.image_comboBox = QtGui.QComboBox(self.groupBox)
        self.image_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.image_comboBox.setObjectName(_fromUtf8("image_comboBox"))
        self.image_comboBox.addItem(_fromUtf8(""))
        self.image_comboBox.setItemText(0, _fromUtf8(""))
        self.image_comboBox.addItem(_fromUtf8(""))
        self.image_comboBox.setItemText(1, _fromUtf8("bmp-4"))
        self.image_comboBox.addItem(_fromUtf8(""))
        self.image_comboBox.setItemText(2, _fromUtf8("bmp-8"))
        self.image_comboBox.addItem(_fromUtf8(""))
        self.image_comboBox.setItemText(3, _fromUtf8("jpeg"))
        self.image_comboBox.addItem(_fromUtf8(""))
        self.image_comboBox.setItemText(4, _fromUtf8("png"))
        self.verticalLayout_5.addWidget(self.image_comboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.archive_comboBox = QtGui.QComboBox(self.groupBox)
        self.archive_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.archive_comboBox.setObjectName(_fromUtf8("archive_comboBox"))
        self.archive_comboBox.addItem(_fromUtf8(""))
        self.archive_comboBox.setItemText(0, _fromUtf8(""))
        self.archive_comboBox.addItem(_fromUtf8(""))
        self.archive_comboBox.setItemText(1, _fromUtf8("rar"))
        self.archive_comboBox.addItem(_fromUtf8(""))
        self.archive_comboBox.setItemText(2, _fromUtf8("zip"))
        self.verticalLayout_3.addWidget(self.archive_comboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.opt_exclude_cover = QtGui.QCheckBox(self.groupBox_2)
        self.opt_exclude_cover.setObjectName(_fromUtf8("opt_exclude_cover"))
        self.verticalLayout.addWidget(self.opt_exclude_cover)
        self.opt_exclude_rgb = QtGui.QCheckBox(self.groupBox_2)
        self.opt_exclude_rgb.setObjectName(_fromUtf8("opt_exclude_rgb"))
        self.verticalLayout.addWidget(self.opt_exclude_rgb)
        self.opt_exclude = QtGui.QCheckBox(self.groupBox_2)
        self.opt_exclude.setObjectName(_fromUtf8("opt_exclude"))
        self.verticalLayout.addWidget(self.opt_exclude)
        self.opt_exclude_list = QtGui.QLineEdit(self.groupBox_2)
        self.opt_exclude_list.setEnabled(False)
        self.opt_exclude_list.setObjectName(_fromUtf8("opt_exclude_list"))
        self.verticalLayout.addWidget(self.opt_exclude_list)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(45, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.opt_scale = QtGui.QLineEdit(self.groupBox_3)
        self.opt_scale.setMinimumSize(QtCore.QSize(0, 0))
        self.opt_scale.setObjectName(_fromUtf8("opt_scale"))
        self.horizontalLayout.addWidget(self.opt_scale)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(45, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.opt_quality = QtGui.QSlider(self.groupBox_3)
        self.opt_quality.setMinimumSize(QtCore.QSize(0, 0))
        self.opt_quality.setMaximum(100)
        self.opt_quality.setProperty(_fromUtf8("value"), 85)
        self.opt_quality.setOrientation(QtCore.Qt.Horizontal)
        self.opt_quality.setTickPosition(QtGui.QSlider.TicksBelow)
        self.opt_quality.setObjectName(_fromUtf8("opt_quality"))
        self.horizontalLayout_2.addWidget(self.opt_quality)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(45, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.opt_level = QtGui.QLineEdit(self.groupBox_3)
        self.opt_level.setMinimumSize(QtCore.QSize(0, 0))
        self.opt_level.setObjectName(_fromUtf8("opt_level"))
        self.horizontalLayout_3.addWidget(self.opt_level)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.about_pushButton = QtGui.QPushButton(self.centralwidget)
        self.about_pushButton.setObjectName(_fromUtf8("about_pushButton"))
        self.horizontalLayout_9.addWidget(self.about_pushButton)
        self.statusBar = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setText(_fromUtf8(""))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout_9.addWidget(self.statusBar)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_9.addWidget(self.progressBar)
        spacerItem2 = QtGui.QSpacerItem(198, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.cancel_pushButton = QtGui.QPushButton(self.centralwidget)
        self.cancel_pushButton.setEnabled(False)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout_9.addWidget(self.cancel_pushButton)
        self.convert_pushButton = QtGui.QPushButton(self.centralwidget)
        self.convert_pushButton.setObjectName(_fromUtf8("convert_pushButton"))
        self.horizontalLayout_9.addWidget(self.convert_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_7.setBuddy(self.select_lineEdit)
        self.label_3.setBuddy(self.opt_size)
        self.label_8.setBuddy(self.output_lineEdit)
        self.label.setBuddy(self.image_comboBox)
        self.label_2.setBuddy(self.archive_comboBox)
        self.label_4.setBuddy(self.opt_scale)
        self.label_5.setBuddy(self.opt_quality)
        self.label_6.setBuddy(self.opt_level)
        self.statusBar.setBuddy(self.pushButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Comic Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Select file or directory to convert:", None, QtGui.QApplication.UnicodeUTF8))
        self.select_lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can use wildcard</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e.g. <span style=\" font-weight:600;\">*.cbr</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.select_pushButton.setText(QtGui.QApplication.translate("MainWindow", "&Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_pushButton.setText(QtGui.QApplication.translate("MainWindow", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_recursive.setText(QtGui.QApplication.translate("MainWindow", "process subdirectories recursively", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "process only files larger then size (in MB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Output directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.output_lineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default is <span style=\" font-weight:600;\">_converted</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">in proccesed directory</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.output_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "image format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "archive format", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Exclude", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude_cover.setToolTip(QtGui.QApplication.translate("MainWindow", "Excludes comic book cover page", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude_cover.setText(QtGui.QApplication.translate("MainWindow", "cover", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude_rgb.setToolTip(QtGui.QApplication.translate("MainWindow", "Excludes images with RGB colorspace", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude_rgb.setText(QtGui.QApplication.translate("MainWindow", "color images", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Comma separated list</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e.g. <span style=\" font-weight:600;\">0,2,13</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_exclude.setText(QtGui.QApplication.translate("MainWindow", "images", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("MainWindow", "scale the image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_scale.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">scale images, you can use percents</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e.g. <span style=\" font-weight:600;\">80%</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">image geometry</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e.g. <span style=\" font-weight:600;\">1600x1200</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">or just image width</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e.g. <span style=\" font-weight:600;\">1200</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_scale.setText(QtGui.QApplication.translate("MainWindow", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("MainWindow", "image quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "quality", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_quality.setToolTip(QtGui.QApplication.translate("MainWindow", "Image quality,\n"
"affects JPEG and PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("MainWindow", "adjust the level of image contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "level", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_level.setToolTip(QtGui.QApplication.translate("MainWindow", "Adjust the level of image contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.opt_level.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.about_pushButton.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.convert_pushButton.setText(QtGui.QApplication.translate("MainWindow", "&Convert", None, QtGui.QApplication.UnicodeUTF8))

import cc_rc
